# Generated by Django 4.2.16 on 2025-02-18 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_auctionlisting_coment_bid"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Coment",
            new_name="Comment",
        ),
    ]
